# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET build and test using artifacts

env:
  artifact_name: dotnet-specflow-build
  default_output_target_path: bin/Debug/net6.0/

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        project: [ AutomationWeb, AutomationMobile, AutomationAPI ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build "${{ matrix.project }}" --no-restore

      - name: Zip build artifact
        run: zip ${{ matrix.project }}.zip ./${{ matrix.project }}/$default_output_target_path -r

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.ref_name }}_${{ matrix.project }}
          path: ${{ matrix.project }}.zip
          retention-days: 5
  
  run-tests:
    needs: [ build ]
    strategy:
      matrix:
        project: [ AutomationWeb, AutomationMobile, AutomationAPI ]
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.ref_name }}_${{ matrix.project }}

      - name: Unzip build artifact
        run: unzip ${{ matrix.project }}.zip

      - name: Test
        env:
          Secrets__BackOfficeUsername: ${{ secrets.SECRETS__BACKOFFICEUSERNAME }}
          Secrets__BackOfficePassword: ${{ secrets.SECRETS__BACKOFFICEPASSWORD }}
        run: dotnet test "${{ matrix.project }}" --no-build --verbosity normal
