# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

env:
  artifact_name: dotnet-specflow-build
  default_output_target_path: bin/Debug/net6.0/
  project_assemblies_to_build: [AutomationWeb, AutomationMobile, AutomationAPI]

on:
  push:
#    branches: [ "main" ]
  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        project: ${{ vars.project_assemblies_to_build }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build "${{ matrix.project }}" --no-restore
      
    - name: Zip build artifact
      run: |
        ls
        ls AutomationFramework
        ls AutomationWeb
        ls AutomationMobile
        ls AutomationAPI
        echo zip ${{ matrix.project }}.zip ./${{ matrix.project }}/$default_output_target_path -r
        zip ${{ matrix.project }}.zip ./${{ matrix.project }}/$default_output_target_path -r
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.project }}
        path: ${{ matrix.project }}.zip
      
  run-tests:
    needs: [build]
    strategy:
      matrix:
        project: [AutomationWeb, AutomationMobile, AutomationAPI]
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
#      - name: Restore dependencies
#        run: dotnet restore
#      - name: Build
#        run: dotnet build --no-restore
      
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.project }}
          
      - name: Unzip build artifact
        run: unzip ${{ matrix.project }}.zip
        
      - name: Test
        env:
          Secrets__BackOfficeUsername: ${{ secrets.SECRETS__BACKOFFICEUSERNAME }}
          Secrets__BackOfficePassword: ${{ secrets.SECRETS__BACKOFFICEPASSWORD }}
        run: dotnet test "${{ matrix.project }}" --no-build --verbosity normal
